### ISSUE TITLE
Not available in firefox 57

### ISSUE THREAD

**Issue by 131** [tg-x/certpatrol#1]
Any plan here :cry:  ?

**Comment by Hillside502** [comment]
Dead as a dodo --- dev doesn't even respond to this issue!

**Comment by ghost** [comment]
There are now plans to make this compatible with newer Firefox. This is an addon which uses XUL.
Github is, as far as I am aware, not the primary place of development but just one of many.
http://patrol.psyced.org would hold updates.

**Comment by cbiedl** [comment]
I recall a remark by lynX that Firefox 62 was about to introduce a new api to access cert data - that could be all needed to re-create certpatrol. Which I hope to see some day.

**Comment by shirishag75** [comment]
I  have firefox 68.0.x and would be able to help with any testing if needed provided there is a place to collaborate. @ng-0

**Comment by cbiedl** [comment]
Mind to explain what you're doing here @131?

**Comment by mrx23dot** [comment]
As I heard Firefox now has certificate pinning built in.
But what if the original CA was compromised by the NSA?
Is there an addon that would majority vote CAs?
